# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

Dir.chdir("..") do
	
	if ENV["ENV_PATH"]

		env_location = ENV["ENV_PATH"]

	    puts "Load .env file at #{ File.expand_path(ENV["ENV_PATH"])}"

	    Dotenv.overload env_location+".default"
	    Dotenv.overload env_location

	    environment = lane_context[SharedValues::ENVIRONMENT]
	    unless environment.nil?
	        puts "Load .env file at #{environment}"
	        Dotenv.overload env_location + environment
	    end
	  end


	
	# app name
	app_name_short = ENV["APP_NAME_SHORT"]

	# unity build paths
	unity_builds_path = File.expand_path(ENV["UNITY_BUILDS_PATH"])

	platform_win = "win"
	platform_macos = "macos"
	platform_linux = "linux"
	platform_ios = "ios"
	platform_android = "android"

	unity_android_appbundle_build_path_base = File.join(unity_builds_path,platform_android,"appbundle")
	unity_android_withobb_build_path_base = File.join(unity_builds_path,platform_android,"with-obb")
	unity_android_withoutobb_build_path_base = File.join(unity_builds_path,platform_android,"without-obb")
	unity_macos_build_path_base = File.join(unity_builds_path,platform_macos)
	unity_win_build_path_base = File.join(unity_builds_path,platform_win)
	unity_linux_build_path_base= File.join(unity_builds_path,platform_linux)
	unity_ios_build_path_base = File.join(unity_builds_path,platform_ios)

	ios_xcode_output_path = File.join(unity_ios_build_path_base,"ipa")
	ios_ipa_name = "#{app_name_short}.ipa"
	ios_ipa_path = File.join(ios_xcode_output_path,ios_ipa_name)

	unity_android_appbundle_build_path = File.join(unity_android_appbundle_build_path_base,app_name_short+".aab")
	unity_android_withobb_build_path = File.join(unity_android_withobb_build_path_base,app_name_short+".apk")
	unity_android_withoutobb_build_path = File.join(unity_android_withoutobb_build_path_base,app_name_short+".apk")	
	unity_macos_build_path = File.join(unity_macos_build_path_base,app_name_short+".app")
	unity_win_build_path = File.join(unity_win_build_path_base,app_name_short+".exe")
	unity_linux_build_path = File.join(unity_linux_build_path_base,app_name_short)
	unity_ios_build_path = File.join(unity_ios_build_path_base,app_name_short)


	archive_path = File.expand_path(ENV["ARCHIVE_PATH"])

	# unity project path
	unity_project_path = File.expand_path(ENV["FL_UNITY_PROJECT_PATH"])

	# google play
	google_play_mode = ENV["GOOGLE_PLAY_MODE"]

	store_googleplay_path = File.expand_path(ENV["GOOGLE_PLAY_STOREDATA_PATH"])

	# ios
	store_ios_path = File.expand_path(ENV["IOS_STOREDATA_PATH"])
	store_ios_screenshots_path = File.join(store_ios_path,"screenshots")
	store_ios_metadata_path = File.join(store_ios_path,"metadata")
	store_ios_project_path = File.join(unity_ios_build_path,"Unity-iPhone.xcodeproj")

	# itch.io
	store_itch_content_path = File.expand_path(ENV["ITCH_CONTENT_PATH"])
	store_itch_content_linux_path = File.join(store_itch_content_path,platform_linux)
	store_itch_content_win_path = File.join(store_itch_content_path,platform_win)
	store_itch_content_macos_path = File.join(store_itch_content_path,platform_macos)

	# steam
	store_steam_content_path = File.expand_path(ENV["STEAM_CONTENT_PATH"])
	store_steam_content_linux_path = File.join(store_steam_content_path,platform_linux)
	store_steam_content_win_path = File.join(store_steam_content_path,platform_win)
	store_steam_content_macos_path = File.join(store_steam_content_path,platform_macos)
	store_steam_vdf_path = File.expand_path(ENV["STEAM_VDF_PATH"])
	store_steam_validate_url = "steam://validate/"+ENV["APP_STEAM_ID"]
	steam_deploy_enabled = ENV["STEAM_DEPLOY_ENABLED"] == "true"

	#itch
	itch_deploy_enabled = ENV["ITCH_DEPLOY_ENABLED"] == "true"

	def getPassword(serviceName,accountName)

		fullServiceName = "#{serviceName}:#{accountName}"
		UI.message "Getting password for service '#{fullServiceName}', account '#{accountName}' from keychain"

		cmd = "security find-generic-password -a #{accountName} -s #{fullServiceName} -w -g | tr -d '\n'"
		
		pw = sh( command:cmd,log:false)
		return pw
	end


	def zipIt(src_dir,archive_path,platform)

		ignores = [".DS_Store","version","commit"]
		debug_file_list = ["*_BurstDebugInformation_DoNotShip*","*.debug","*.dSYM.zip","*.pdb"]

		git_commit = getBuildCommit(src_dir)
		version = getBuildVersion(src_dir)

		base_name = "#{version}-#{git_commit}"
		dst = File.join(archive_path,base_name,"#{base_name}-#{platform}")
		UI.message "Archiving version #{version}, #{platform} (#{git_commit}) "

		UI.message "Zipping #{src_dir} to #{dst}..."
		out_path = dst+".zip"
		File.delete(out_path) if File.exist?(out_path)

		zip(
		  path: src_dir,
		  output_path:out_path,
		  exclude: [].concat(ignores).concat(debug_file_list)
		)

		debug_file_found = false
		for pattern in debug_file_list do   

			if Dir.glob(File.join(src_dir,pattern)).length > 0
				debug_file_found = true
				break
			end 
		end   

		if debug_file_found == true
			UI.message "Debug files found, creating debug package..."

			UI.message "Zipping #{src_dir} to #{dst}..."
			out_path_debug = dst+"-debug.zip"
			File.delete(out_path_debug) if File.exist?(out_path_debug)

			zip(
			  path: src_dir,
			  output_path:out_path_debug,
			  include: debug_file_list,
			  exclude: [].concat(ignores)
			)
		end
	end

	def getBuildVersion(build_path)
		return File.read(File.join(build_path,"version")).strip
	end

	def getBuildCommit(build_path)
		return File.read(File.join(build_path,"commit")).strip
	end



	#print unity_builds_path
	#print "\n"
	#print unity_project_path
	#print "\n"
	#print archive_path
	#print "\n"

	def send_mail(success,subject,message,app_link="")

		mailgun_apikey_file = ENV["MAILGUN_API_KEY_FILE"]
		mailgun_apikey_file_fullpath = File.expand_path(mailgun_apikey_file)
		if(!File.file?(mailgun_apikey_file_fullpath))
			UI.message "No mailgun key file found at #{mailgun_apikey_file_fullpath}, skipping notification mail."
			return
		end
		mailgun_apikey = File.open( mailgun_apikey_file_fullpath, &:readline).gsub(/\s+/, "")
		mailgun(
			apikey:mailgun_apikey,
			from:ENV["APP_NAME_NICE"]+" Build Status",
			subject:subject,
			success: success,
			message: subject+"<br>"+message,
			app_link: app_link
		)
	end


	def syncBuilds(src_dir,dst_dir)
		fastlane_require 'fileutils'
		fastlane_require 'shellwords'
		FileUtils.mkdir_p dst_dir # this runs from the fastlane dir

		rsync(
			extra:"-ahrLv --delete --delete-excluded --exclude={.DS_Store,/steam_appid.txt,/version,/commit,/*_BurstDebugInformation_DoNotShip,/*.pdb,/*.debug}",
			source:(src_dir+'/').shellescape,
		destination:(dst_dir+'/').shellescape)
	end


	default_platform(:ios)

	platform :android do

		desc "Android – Deploy"
		lane :deploy do

			begin
				version = set_version
				build_unity_withoutobb(version:version)

				case google_play_mode
					when "apkwithobb" then
						build_unity_withobb(version:version)
					when "appbundle" then
						build_unity_appbundle(version:version)
				end
				zip_builds
				upload_googleplay
			rescue => ex
				send_mail false,"Android Deploy failed",ex.to_s
				raise ex
			end
				
			send_mail true,"Android Deploy successful","It is now available on Google Play","https://play.google.com/store/apps/details?id="+CredentialsManager::AppfileConfig.try_fetch_value(:package_name)

		end

		desc "Android – Zip Builds"
		lane :zip_builds do

			zipIt(unity_android_withoutobb_build_path_base, archive_path,"android-apk")

			case google_play_mode
				when "apkwithobb" then
					zipIt(unity_android_withobb_build_path_base, archive_path,"android-apkwithobb")
				when "appbundle" then
					zipIt(unity_android_appbundle_build_path_base,archive_path,"android-appbundle")
			end
		end


		desc "Android – Set version"
		lane :set_version do

		prev_versions = google_play_track_version_codes(track:"internal")
		if prev_versions[0]
			new_version = prev_versions[0]+1
		else
			prev_versions = google_play_track_version_codes(track:"production") # production
			if prev_versions[0]
				new_version = prev_versions[0]+1
			else
				new_version = 1
			end
		end
		new_version
		end


		desc "Android (apk without obb) – Build in Unity"
		lane :build_unity_withoutobb do |options|

			version = options[:version] || 1
			unity_build(
				build_target: "Android",
				build_path: unity_android_withoutobb_build_path,
				obb:0,
			build_version: version.to_s )
		end



		desc "Android (apk with obb) – Build in Unity"
		lane :build_unity_withobb do |options|

			version = options[:version] || 1
			unity_build(
				build_target: "Android",
				build_path: unity_android_withobb_build_path,
				obb:1,
			build_version: version.to_s )
		end


		desc "Android (appbundle) – Build in Unity"
		lane :build_unity_appbundle do |options|

			version = options[:version] || 1
			unity_build(
				build_target: "Android",
				build_path: unity_android_appbundle_build_path,
				android_app_bundle:1,
			build_version: version.to_s )
		end

		desc "Android – Upload to google play (internal)"
		lane :upload_googleplay do
			track = "internal"

			case google_play_mode
			when "apk" then
				upload_to_play_store(
					track:track,
					apk:unity_android_withoutobb_build_path,
					skip_upload_metadata:true,
					skip_upload_images:true,
				skip_upload_screenshots:true)
			when "apkwithobb" then
				upload_to_play_store(
					track:track,
					apk:unity_android_withobb_build_path,
					skip_upload_metadata:true,
					skip_upload_images:true,
				skip_upload_screenshots:true)
			when "appbundle" then
				upload_to_play_store(
					track:track,
					aab:unity_android_appbundle_build_path,
					skip_upload_metadata:true,
					skip_upload_images:true)
			end
				
		end

		desc "Android – Upload to google play (metadata)"
		lane :upload_googleplay_metadata do
			upload_to_play_store(
				metadata_path:store_googleplay_path
			)
		end

	end
	platform :mac do

		desc "Standalone – Deploy"
		lane :deploy do

			# send_mail true,"Standalone Deploy started","",store_steam_validate_url

			begin
				build_unity
				sign_mac
				if ENV["SKIP_NOTARIZE"] != "true"
					notarize_mac
				end
				zip_builds

				if steam_deploy_enabled
					sync_upload_steam
				end

				if itch_deploy_enabled
					sync_upload_itch
				end
			rescue => ex
				send_mail false,"Standalone Deploy failed",ex.to_s
				raise ex
			end

			send_mail true,"Standalone Deploy successful","It is now available on Steam",store_steam_validate_url

		end
	 
		desc "Standalone – Build in Unity"
		lane :build_unity do


			unity_build(
				build_target: "StandaloneOSX",
				build_path: unity_macos_build_path
			)


			unity_build(
				build_target: "StandaloneWindows64",
				build_path: unity_win_build_path
				 )


			unity_build(
				build_target: "StandaloneLinux64",
				build_path: unity_linux_build_path
			)
		end

		desc "Standalone – Sign Mac Build"
		lane :sign_mac do

			UI.message ENV["CODESIGN_ADDITIONAL_BUNDLES"]


			additionalBundles = (ENV["CODESIGN_ADDITIONAL_BUNDLES"] || "").split(/\s*,\s*/)
			additionalBundles.each do |b|
			  codesign_mac(
			  	target:File.join(unity_macos_build_path,b)
			  	)
			end
			
			codesign_mac(
				target:unity_macos_build_path,
				)
			gatekeeper_verify(
				target:unity_macos_build_path)
		end

		desc "Standalone – Notarize Mac Build"
		lane :notarize_mac do

			#UI.message cmd
			ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = getPassword(
				"fastlane.notarize",
				ENV["FL_NOTARIZE_USERNAME"])


			notarize(
				package:unity_macos_build_path,
				print_log:true)

			# remove zip file created by notarize
			zip_path = "#{unity_macos_build_path}.zip"
			File.delete(zip_path) if File.exist?(zip_path)

			gatekeeper_verify(
				target:unity_macos_build_path)
		end

		desc "Standalone – Zip Builds"
		lane :zip_builds do

			zipIt(unity_linux_build_path_base,archive_path,"linux")
			zipIt(unity_macos_build_path_base,archive_path,"macos")
			zipIt(unity_win_build_path_base,archive_path,"win")
		end

		desc "Standalone – Sync Builds & Upload to Steam"
		lane :sync_upload_steam do

			syncBuilds(unity_linux_build_path_base,store_steam_content_linux_path);
			syncBuilds(unity_macos_build_path_base,store_steam_content_macos_path);
			syncBuilds(unity_win_build_path_base,store_steam_content_win_path);

			upload_to_steam(
				vdf_path: store_steam_vdf_path
			)
		end
		desc "Standalone – Sync BUilds & Upload to itch.io"
		lane :sync_upload_itch do


			syncBuilds(unity_linux_build_path_base,store_itch_content_linux_path);
			syncBuilds(unity_macos_build_path_base,store_itch_content_macos_path);
			syncBuilds(unity_win_build_path_base,store_itch_content_win_path);

			butler_push(
				data_path: store_itch_content_linux_path,
				channel:"linux",
				version: getBuildVersion(unity_linux_build_path_base)
			)
			butler_push(
				data_path: store_itch_content_macos_path,
				channel:"macos",
				version: getBuildVersion(unity_macos_build_path_base)
			)
			butler_push(
				data_path: store_itch_content_win_path,
				channel:"win",
				version: getBuildVersion(unity_win_build_path_base)
			)
		end

	end


	platform :ios do

		desc "iOS – Deploy"
		lane :deploy do
			app_id = "0"# replace

			testflight_link = "https://beta.itunes.apple.com/v1/app/"+app_id
		#send_mail true,"iOS Build started","",testflight_link
	 
			begin
				build_unity
				set_version
				build_xcode
				zip_builds
				upload_testflight_internal

			rescue => ex
				send_mail false,"iOS Build failed",ex.to_s
				raise ex
			end

			
			send_mail true,"iOS Build successful","It will soon be available on testflight",testflight_link
		end

		desc "iOS – Build in Unity"
		lane :build_unity do
			unity_build(
				project_path: unity_project_path,
				build_target: "iOS",
				build_path: unity_ios_build_path
				 )
		end



		desc "iOS – Set Version"
		lane :set_version do
			scheme = "Unity-iPhone"

			version = ENV["ENABLE_IOS_VERSION_WORKAROUND"] ? nil : get_version_number(xcodeproj: store_ios_project_path, target: 'Unity-iPhone')

			 latest_build_number = latest_testflight_build_number(
				app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
				version: version
		)
		 increment_build_number({build_number: latest_build_number + 1,xcodeproj:store_ios_project_path})
		 end

		desc "iOS – Build in XCode"
		lane :build_xcode do
			scheme = "Unity-iPhone"

		  
			 get_certificates(
			 	output_path:"certificates"
			 )   
			 get_provisioning_profile(
			 	output_path: "provisioning_profiles"
			 ) 
			 if ENV["IOS_USE_STICKERS"] == "true"
		    		get_provisioning_profile(app_identifier: "#{ENV['IOS_APP_IDENTIFIER']}.Stickers")
			end

			build_app(
				output_directory:ios_xcode_output_path,
				output_name: ios_ipa_name, 
				xcargs: "-allowProvisioningUpdates",
				export_team_id:ENV["IOS_DEV_TEAM_ID"],
				silent:true,
				scheme: scheme,
				project:store_ios_project_path)

			# copy debug info to output dir, where it will be read for archiving
			files_to_copy = ["#{app_name_short}_BurstDebugInformation_DoNotShip","commit","version"]

			UI.message "Copying additional files from unity build path to xcode build output path (for archiving)."
			UI.message "Unity build path: #{unity_ios_build_path_base}" 
			UI.message "XCode build output path: #{ios_xcode_output_path}"
			files_to_copy.each do |item|
				src = File.join(unity_ios_build_path_base,item)
				dst = File.join(ios_xcode_output_path,item)

				if File.exist?(src)
					UI.message "Copying '#{item}' ..."
					FileUtils.rm_rf(dst) 
					FileUtils.cp_r(src,ios_xcode_output_path)
				end
			end
						
		end
		desc "iOS – Zip Builds"
		lane :zip_builds do

			zipIt(ios_xcode_output_path,archive_path,"ios")
		end
		
		desc "iOS – Push ipa to TestFlight (Internal, skip processing)"
		lane :upload_testflight_internal do

			ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = getPassword(
				"fastlane.testflight",
				CredentialsManager::AppfileConfig.try_fetch_value(:apple_id))

			upload_to_testflight(
				ipa:ios_ipa_path,
				skip_waiting_for_build_processing:true,
				)
		end

		desc "iOS – Submit App Store info (including Screenshots)"
		lane :submit_info do
			deliver(
				skip_binary_upload: true,
				screenshots_path:ios_screenshots_path,
				metadata_path:ios_metadata_path
			)
		end

		desc "send mail test"
		lane :mail_test do

			begin
				#raise 'An error has occured'

			rescue => ex
				send_mail false,"Error",ex.to_s,""
				raise ex
			end

			send_mail true,"Success","Message","https://playables.net"

		end

	end
end
